
# Bright colors
[colors.bright]
black = '#414868'
red = '#f38ba8'
green = '#a6e3a1'
yellow = '#f9e2af'
blue = '#89b4f9'
magenta = '#cba6f7'
cyan = '#74c7ec'
white = '#cdd6f4'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#414868'
red = '#f38ba8'
green = '#a6e3a1'
yellow = '#f9e2af'
blue = '#89b4f9'
magenta = '#cba6f7'
cyan = '#74c7ec'
white = '#cdd6f4'

[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#fab387'

[[colors.indexed_colors]]
index = 17
color = '#f38ba8'


