return {
	{
		"nvim-treesitter/nvim-treesitter",
		tag = "v0.9.1",
		opts = {
			ensure_installed = {
				"javascript",
				"typescript",
				"css",
				"gitignore",
				"graphql",
				"http",
				"json",
        "yaml",
        "bash",
        "html",
        "regex",
        "tsx",
				"scss",
        "python",
        "query",
				"sql",
				"vim",
				"lua",
        "markdown",
        "markdown_inline",
			},
      ignore_install = { "xml", "printf" },
			query_linter = {
				enable = true,
				use_virtual_text = true,
				lint_events = { "BufWrite", "CursorHold" },
			},
		},
	},
}
